/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


/**
 *
 * @author florence
 */
public class LogIn extends javax.swing.JPanel {

    /**
     * Creates new form SignUp_1
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogIn = new javax.swing.JLabel();
        txtCreateFreeAccount = new javax.swing.JLabel();
        lblWelcome_LogIn = new javax.swing.JLabel();
        lblUsername_LogIn = new javax.swing.JLabel();
        txtEmail_LogIn = new javax.swing.JTextField();
        txtPassword_LogIn = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        txtUsername_LogIn = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        imgIcon_LogIn = new javax.swing.JLabel();
        chckbxRememberMe = new javax.swing.JCheckBox();
        lblEmail_LogIn = new javax.swing.JLabel();
        iconLogo = new javax.swing.JLabel();
        txtDontHaveAnAccount = new javax.swing.JLabel();
        txtForgotPassword = new javax.swing.JLabel();
        iconUsername = new javax.swing.JLabel();
        iconEmailAddress = new javax.swing.JLabel();
        iconPassword = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1024, 728));
        setPreferredSize(new java.awt.Dimension(1024, 728));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogIn.setFont(new java.awt.Font("Segoe UI", 1, 52)); // NOI18N
        lblLogIn.setText("Log In");
        add(lblLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        txtCreateFreeAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCreateFreeAccount.setForeground(new java.awt.Color(37, 99, 235));
        txtCreateFreeAccount.setText("Create free account");
        add(txtCreateFreeAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 660, -1, 20));

        lblWelcome_LogIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWelcome_LogIn.setForeground(new java.awt.Color(82, 82, 91));
        lblWelcome_LogIn.setText("<html> Welcome to Readme Library Management <br> System!");
        add(lblWelcome_LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        lblUsername_LogIn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblUsername_LogIn.setText("Username");
        add(lblUsername_LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        txtEmail_LogIn.setBackground(new java.awt.Color(248, 250, 252));
        txtEmail_LogIn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtEmail_LogIn.setForeground(new java.awt.Color(127, 126, 126));
        txtEmail_LogIn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 1, true));
        txtEmail_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail_LogInActionPerformed(evt);
            }
        });
        add(txtEmail_LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 280, 30));

        txtPassword_LogIn.setBackground(new java.awt.Color(248, 250, 252));
        txtPassword_LogIn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtPassword_LogIn.setForeground(new java.awt.Color(127, 127, 127));
        txtPassword_LogIn.setText("jPasswordField1");
        txtPassword_LogIn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 1, true));
        txtPassword_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassword_LogInActionPerformed(evt);
            }
        });
        add(txtPassword_LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 280, 30));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblPassword.setText("Password");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        txtUsername_LogIn.setBackground(new java.awt.Color(248, 250, 252));
        txtUsername_LogIn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtUsername_LogIn.setForeground(new java.awt.Color(127, 126, 126));
        txtUsername_LogIn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 1, true));
        txtUsername_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsername_LogInActionPerformed(evt);
            }
        });
        add(txtUsername_LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 280, 30));

        btnSignUp.setBackground(new java.awt.Color(51, 102, 255));
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Sign In");
        btnSignUp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 1, true));
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 130, 40));

        imgIcon_LogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1-01 1.png"))); // NOI18N
        imgIcon_LogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(imgIcon_LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 700, 660));

        chckbxRememberMe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chckbxRememberMe.setText("Remember me");
        chckbxRememberMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbxRememberMeActionPerformed(evt);
            }
        });
        add(chckbxRememberMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, -1));

        lblEmail_LogIn.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblEmail_LogIn.setText("Email Address");
        add(lblEmail_LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        iconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo-01 1.png"))); // NOI18N
        add(iconLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 130, 130));

        txtDontHaveAnAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDontHaveAnAccount.setForeground(new java.awt.Color(82, 82, 91));
        txtDontHaveAnAccount.setText("Don't have an account?");
        add(txtDontHaveAnAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, -1, -1));

        txtForgotPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtForgotPassword.setForeground(new java.awt.Color(37, 99, 235));
        txtForgotPassword.setText("Forgot Password?");
        add(txtForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, -1, 20));

        iconUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/readme/icons8-user-16.png"))); // NOI18N
        add(iconUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 20, 40));

        iconEmailAddress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/readme/icons8-email-16.png"))); // NOI18N
        add(iconEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 20, 40));

        iconPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/readme/icons8-password-16.png"))); // NOI18N
        add(iconPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 20, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmail_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail_LogInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail_LogInActionPerformed

    private void txtUsername_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsername_LogInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsername_LogInActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void chckbxRememberMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbxRememberMeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chckbxRememberMeActionPerformed

    private void txtPassword_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassword_LogInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassword_LogInActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUp;
    private javax.swing.JCheckBox chckbxRememberMe;
    private javax.swing.JLabel iconEmailAddress;
    private javax.swing.JLabel iconLogo;
    private javax.swing.JLabel iconPassword;
    private javax.swing.JLabel iconUsername;
    private javax.swing.JLabel imgIcon_LogIn;
    private javax.swing.JLabel lblEmail_LogIn;
    private javax.swing.JLabel lblLogIn;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername_LogIn;
    private javax.swing.JLabel lblWelcome_LogIn;
    private javax.swing.JLabel txtCreateFreeAccount;
    private javax.swing.JLabel txtDontHaveAnAccount;
    private javax.swing.JTextField txtEmail_LogIn;
    private javax.swing.JLabel txtForgotPassword;
    private javax.swing.JPasswordField txtPassword_LogIn;
    private javax.swing.JTextField txtUsername_LogIn;
    // End of variables declaration//GEN-END:variables
}
