
import java.awt.BorderLayout;
import java.awt.Image;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Judy
 */
public class ViewMore extends javax.swing.JFrame {

    /**
     * Creates new form ViewMore
     */
    public ViewMore() {
        initComponents();
                String className = "com.mysql.cj.jdbc.Driver";
                String url = "jdbc:mysql://localhost:3306/readmedb";
                String user = "root";
                String password = "";
                
                Connection con;
                Statement st;
                ResultSet rs;
                
                
                try {
                    Class.forName(className);
                    con = DriverManager.getConnection(url, user, password);
                    st = con.createStatement();

                    // Compose the SQL query to retrieve all books
                    String query = "SELECT * FROM books";
                    rs = st.executeQuery(query);

                    int count = 1;
                    while (rs.next()) {
                        String bookTitle = rs.getString(2);
                        byte[] imageData = rs.getBytes(10);

                        ByteArrayInputStream inputStream = new ByteArrayInputStream(imageData);
                        Image image = ImageIO.read(inputStream);

                        JLabel bookLabel = new JLabel(bookTitle);
                        JLabel authorLabel = new JLabel(rs.getString(3));
                        JLabel imageLabel = new JLabel(new ImageIcon(image));

                        // Set the position and size of each book's components dynamically
                        int xPos = 10;
                        int yPos = count * 100;
                        int labelWidth = 200;
                        int labelHeight = 20;
                        int imageWidth = 500;
                        int imageHeight = 400;

                        bookLabel.setBounds(xPos, yPos, labelWidth, labelHeight);
                        authorLabel.setBounds(xPos, yPos + labelHeight, labelWidth, labelHeight);
                        imageLabel.setBounds(xPos + labelWidth + 10, yPos, imageWidth, imageHeight);

                        // Add the components to your GUI container (e.g., a JPanel or JFrame)
                        pnlBookPreview.add(bookLabel);
                        pnlBookPreview.add(authorLabel);
                        pnlBookPreview.add(imageLabel);

                        count++;
                    }
                } catch (ClassNotFoundException ex) {
                    System.err.println("Connection error: " + ex.getMessage());
                } catch (SQLException ex) {
                    Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
                    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBookPreview7 = new javax.swing.JPanel();
        lblBook1 = new javax.swing.JLabel();
        lblAuthor1 = new javax.swing.JLabel();
        pnlBookFeatured7 = new javax.swing.JPanel();
        jImage1 = new javax.swing.JLabel();
        btnBorrow14 = new javax.swing.JButton();
        btnBorrow13 = new javax.swing.JButton();
        pnlLeft = new javax.swing.JPanel();
        iconLogo = new javax.swing.JLabel();
        iconLogo1 = new javax.swing.JLabel();
        iconLogo2 = new javax.swing.JLabel();
        iconLogo3 = new javax.swing.JLabel();
        iconLogo4 = new javax.swing.JLabel();
        iconLogo5 = new javax.swing.JLabel();
        iconLogo10 = new javax.swing.JLabel();
        iconLogo11 = new javax.swing.JLabel();
        pnlBookPreview = new javax.swing.JPanel();

        pnlBookPreview7.setBackground(new java.awt.Color(255, 255, 255));

        lblBook1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblBook1.setText("Book Title");

        lblAuthor1.setBackground(new java.awt.Color(153, 153, 153));
        lblAuthor1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblAuthor1.setForeground(new java.awt.Color(153, 153, 153));
        lblAuthor1.setText("Author");

        pnlBookFeatured7.setBackground(new java.awt.Color(196, 196, 196));
        pnlBookFeatured7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        pnlBookFeatured7.setForeground(new java.awt.Color(255, 255, 255));

        jImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlBookFeatured7Layout = new javax.swing.GroupLayout(pnlBookFeatured7);
        pnlBookFeatured7.setLayout(pnlBookFeatured7Layout);
        pnlBookFeatured7Layout.setHorizontalGroup(
            pnlBookFeatured7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        pnlBookFeatured7Layout.setVerticalGroup(
            pnlBookFeatured7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
        );

        btnBorrow14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Bar.png"))); // NOI18N
        btnBorrow14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        btnBorrow13.setText("Borrow");
        btnBorrow13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrow13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBookPreview7Layout = new javax.swing.GroupLayout(pnlBookPreview7);
        pnlBookPreview7.setLayout(pnlBookPreview7Layout);
        pnlBookPreview7Layout.setHorizontalGroup(
            pnlBookPreview7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookPreview7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlBookFeatured7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(pnlBookPreview7Layout.createSequentialGroup()
                .addGroup(pnlBookPreview7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBookPreview7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlBookPreview7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBook1)
                            .addComponent(lblAuthor1)))
                    .addComponent(btnBorrow14, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBookPreview7Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnBorrow13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBookPreview7Layout.setVerticalGroup(
            pnlBookPreview7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookPreview7Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(pnlBookFeatured7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBook1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAuthor1)
                .addGap(5, 5, 5)
                .addComponent(btnBorrow13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBorrow14)
                .addGap(10, 10, 10))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeft.setToolTipText("leftPanel");
        pnlLeft.setName("pnlLeft"); // NOI18N

        iconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Dashboard1.png"))); // NOI18N

        iconLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Logo-01 2.png"))); // NOI18N

        iconLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Group_1.png"))); // NOI18N

        iconLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Vector (1).png"))); // NOI18N

        iconLogo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Group 1698.png"))); // NOI18N

        iconLogo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Friends.png"))); // NOI18N

        iconLogo10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Logout.png"))); // NOI18N
        iconLogo10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconLogo10MouseClicked(evt);
            }
        });

        iconLogo11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Vector 16.png"))); // NOI18N

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconLogo)
                    .addComponent(iconLogo4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(iconLogo11))
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(pnlLeftLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(iconLogo3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLeftLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(iconLogo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iconLogo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iconLogo10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(iconLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconLogo11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(iconLogo4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iconLogo3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iconLogo5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iconLogo2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(iconLogo10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pnlBookPreview.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlBookPreviewLayout = new javax.swing.GroupLayout(pnlBookPreview);
        pnlBookPreview.setLayout(pnlBookPreviewLayout);
        pnlBookPreviewLayout.setHorizontalGroup(
            pnlBookPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 883, Short.MAX_VALUE)
        );
        pnlBookPreviewLayout.setVerticalGroup(
            pnlBookPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBookPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBookPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iconLogo10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconLogo10MouseClicked
        Login log = new Login();
        log.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_iconLogo10MouseClicked

    private void btnBorrow13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrow13ActionPerformed
        // TODO add your handling code here:
        Borrower borrow = new Borrower();
        borrow.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBorrow13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrow13;
    private javax.swing.JButton btnBorrow14;
    private javax.swing.JLabel iconLogo;
    private javax.swing.JLabel iconLogo1;
    private javax.swing.JLabel iconLogo10;
    private javax.swing.JLabel iconLogo11;
    private javax.swing.JLabel iconLogo2;
    private javax.swing.JLabel iconLogo3;
    private javax.swing.JLabel iconLogo4;
    private javax.swing.JLabel iconLogo5;
    private javax.swing.JLabel jImage1;
    private javax.swing.JLabel lblAuthor1;
    private javax.swing.JLabel lblBook1;
    private javax.swing.JPanel pnlBookFeatured7;
    private javax.swing.JPanel pnlBookPreview;
    private javax.swing.JPanel pnlBookPreview7;
    private javax.swing.JPanel pnlLeft;
    // End of variables declaration//GEN-END:variables
}
